import courseImg from "../../assets/images/courses.png";

export const courses = [
  {
    id: 1,
    title: "UI/UX Design for Beginners",
    category: "UI/UX Design",
    price: 98,
    rating: 4,
    duration: "22hr 30min",
    lessons: 34,
    sales: 250,
    image: courseImg,
  },
  {
    id: 2,
    title: "Advanced Web Development",
    category: "Web Development",
    price: 129,
    rating: 5,
    duration: "30hr 45min",
    lessons: 48,
    sales: 320,
    image: courseImg,
  },
  {
    id: 3,
    title: "Digital Marketing Fundamentals",
    category: "Marketing",
    price: 79,
    rating: 4,
    duration: "18hr 15min",
    lessons: 28,
    sales: 180,
    image: courseImg,
  },
  {
    id: 4,
    title: "Python Programming Masterclass",
    category: "Programming",
    price: 110,
    rating: 5,
    duration: "40hr 20min",
    lessons: 60,
    sales: 500,
    image: courseImg,
  },
  {
    id: 5,
    title: "Data Science with Python",
    category: "Data Science",
    price: 150,
    rating: 4,
    duration: "50hr 10min",
    lessons: 45,
    sales: 410,
    image: courseImg,
  },
  {
    id: 6,
    title: "Graphic Design Essentials",
    category: "Graphic Design",
    price: 85,
    rating: 4,
    duration: "25hr 50min",
    lessons: 32,
    sales: 210,
    image: courseImg,
  },
  {
    id: 7,
    title: "Machine Learning for Beginners",
    category: "Data Science",
    price: 140,
    rating: 5,
    duration: "35hr 00min",
    lessons: 40,
    sales: 290,
    image: courseImg,
  },
  {
    id: 8,
    title: "React Native Mobile Development",
    category: "Mobile Development",
    price: 135,
    rating: 5,
    duration: "28hr 10min",
    lessons: 38,
    sales: 270,
    image: courseImg,
  },
  {
    id: 9,
    title: "Introduction to Cloud Computing",
    category: "Cloud Computing",
    price: 95,
    rating: 4,
    duration: "20hr 00min",
    lessons: 25,
    sales: 230,
    image: courseImg,
  },
  {
    id: 10,
    title: "Cybersecurity Basics",
    category: "Cybersecurity",
    price: 99,
    rating: 4,
    duration: "15hr 30min",
    lessons: 20,
    sales: 150,
    image: courseImg,
  },
  {
    id: 11,
    title: "SEO Optimization Techniques",
    category: "Marketing",
    price: 75,
    rating: 4,
    duration: "12hr 45min",
    lessons: 18,
    sales: 200,
    image: courseImg,
  },
  {
    id: 12,
    title: "JavaScript Fundamentals",
    category: "Programming",
    price: 89,
    rating: 5,
    duration: "18hr 00min",
    lessons: 26,
    sales: 310,
    image: courseImg,
  },
  {
    id: 13,
    title: "Introduction to Blockchain",
    category: "Blockchain",
    price: 120,
    rating: 4,
    duration: "27hr 15min",
    lessons: 30,
    sales: 160,
    image: courseImg,
  },
  {
    id: 14,
    title: "Photography Essentials",
    category: "Photography",
    price: 70,
    rating: 4,
    duration: "15hr 50min",
    lessons: 22,
    sales: 180,
    image: courseImg,
  },
  {
    id: 15,
    title: "Digital Illustration with Procreate",
    category: "Digital Art",
    price: 92,
    rating: 5,
    duration: "22hr 10min",
    lessons: 35,
    sales: 260,
    image: courseImg,
  },
];
