import courseImg from "../../assets/images/courses.png"; 

export const courses = [
  {
    id: 1,
    title: "Master React Development",
    description: "Learn how to build modern web applications using React.js.",
    about:
      "This comprehensive course is designed to help you understand the basics as well as advanced concepts of React. By the end of this course, you will have built a real-world web application.",
    duration: "12 Weeks",
    level: "Beginner to Advanced",
    price: 299,
    rating: 5,
    category: "Web Development",
    curriculum: [
      "Week 1: Introduction to React",
      "Week 2: JSX and Components",
      "Week 3: State and Props",
      "Week 4: Handling Events",
      "Week 5: React Hooks",
      "Week 6: Advanced State Management",
      "Week 7: React Router",
      "Week 8: API Integration",
      "Week 9: Forms and Validation",
      "Week 10: Deployment",
      "Week 11: Real-world Project",
      "Week 12: Final Assessment",
    ],
    youtubeVideo: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    image: courseImg,
  },
  {
    id: 2,
    title: "Introduction to Python Programming",
    description: "Learn the fundamentals of Python programming language.",
    about:
      "This course will teach you the basics of Python, data structures, and how to write clean, efficient code.",
    duration: "10 Weeks",
    level: "Beginner",
    price: 199,
    rating: 4, // Rounded rating
    category: "Programming", // Category added
    curriculum: [
      "Week 1: Introduction to Python",
      "Week 2: Data Types and Variables",
      "Week 3: Control Flow",
      "Week 4: Functions",
      "Week 5: Data Structures",
      "Week 6: File Handling",
      "Week 7: Error Handling",
      "Week 8: Modules and Packages",
      "Week 9: Object-Oriented Programming",
      "Week 10: Final Project",
    ],
    youtubeVideo: "https://www.youtube.com/embed/hYzwCsKGRxI",
    image: courseImg,
  },
  {
    id: 3,
    title: "Web Development Bootcamp",
    description: "Become a full-stack web developer in 12 weeks.",
    about:
      "This bootcamp covers everything from HTML, CSS, JavaScript, to backend technologies like Node.js and databases.",
    duration: "12 Weeks",
    level: "Beginner to Intermediate",
    price: 399,
    rating: 5, // Rounded rating
    category: "Web Development", // Category added
    curriculum: [
      "Week 1: HTML & CSS Basics",
      "Week 2: JavaScript Fundamentals",
      "Week 3: Responsive Design",
      "Week 4: Frontend Frameworks",
      "Week 5: Backend Development with Node.js",
      "Week 6: Database Management",
      "Week 7: RESTful APIs",
      "Week 8: Authentication and Authorization",
      "Week 9: Deployment",
      "Week 10: Real-world Project",
      "Week 11: Best Practices",
      "Week 12: Final Assessment",
    ],
    youtubeVideo: "https://www.youtube.com/embed/Oy3RvgC-uRo",
    image: courseImg,
  },
  {
    id: 4,
    title: "Data Science with R",
    description: "Learn data analysis and visualization using R programming.",
    about:
      "This course will introduce you to data science concepts and how to implement them using R. You'll learn data manipulation, visualization, and machine learning techniques.",
    duration: "14 Weeks",
    level: "Intermediate",
    price: 350,
    rating: 5, // Rounded rating
    category: "Data Science", // Category added
    curriculum: [
      "Week 1: Introduction to R",
      "Week 2: Data Manipulation with dplyr",
      "Week 3: Data Visualization with ggplot2",
      "Week 4: Exploratory Data Analysis",
      "Week 5: Statistical Inference",
      "Week 6: Machine Learning Basics",
      "Week 7: Supervised Learning",
      "Week 8: Unsupervised Learning",
      "Week 9: Text Mining",
      "Week 10: Time Series Analysis",
      "Week 11: Data Science Project",
      "Week 12: Final Assessment",
      "Week 13: Industry Applications",
      "Week 14: Capstone Project",
    ],
    youtubeVideo: "https://www.youtube.com/embed/xK7Y4O3o0S4",
    image: courseImg,
  },
  {
    id: 5,
    title: "Graphic Design Fundamentals",
    description: "Learn the basics of graphic design and visual communication.",
    about:
      "This course covers key design principles, typography, and color theory, along with practical projects to enhance your design skills.",
    duration: "8 Weeks",
    level: "Beginner",
    price: 180,
    rating: 4, // Rounded rating
    category: "UI/UX Design", // Category added
    curriculum: [
      "Week 1: Introduction to Graphic Design",
      "Week 2: Design Principles",
      "Week 3: Typography",
      "Week 4: Color Theory",
      "Week 5: Layout Design",
      "Week 6: Adobe Photoshop Basics",
      "Week 7: Adobe Illustrator Basics",
      "Week 8: Portfolio Development",
    ],
    youtubeVideo: "https://www.youtube.com/embed/qTzHSD7G0Ng",
    image: courseImg,
  },
  {
    id: 6,
    title: "Digital Marketing Masterclass",
    description: "Master the art of digital marketing strategies and tools.",
    about:
      "This course teaches you how to create effective digital marketing campaigns using SEO, content marketing, and social media strategies.",
    duration: "10 Weeks",
    level: "Beginner to Intermediate",
    price: 250,
    rating: 4, // Rounded rating
    category: "Digital Marketing", // Category added
    curriculum: [
      "Week 1: Introduction to Digital Marketing",
      "Week 2: SEO Basics",
      "Week 3: Content Marketing Strategies",
      "Week 4: Social Media Marketing",
      "Week 5: Email Marketing",
      "Week 6: Google Ads",
      "Week 7: Analytics and Tracking",
      "Week 8: Building Your Brand",
      "Week 9: Marketing Automation",
      "Week 10: Final Project",
    ],
    youtubeVideo: "https://www.youtube.com/embed/2nbI45t7e74",
    image: courseImg,
  },
  {
    id: 7,
    title: "Introduction to Machine Learning",
    description: "Learn the basics of machine learning algorithms and models.",
    about:
      "This course introduces machine learning concepts, popular algorithms, and how to implement them using Python libraries.",
    duration: "10 Weeks",
    level: "Intermediate",
    price: 299,
    rating: 5, // Rounded rating
    category: "Data Science", // Category added
    curriculum: [
      "Week 1: Introduction to Machine Learning",
      "Week 2: Supervised vs Unsupervised Learning",
      "Week 3: Linear Regression",
      "Week 4: Decision Trees",
      "Week 5: Support Vector Machines",
      "Week 6: Neural Networks",
      "Week 7: Model Evaluation and Tuning",
      "Week 8: Clustering Techniques",
      "Week 9: Feature Engineering",
      "Week 10: Final Project",
    ],
    youtubeVideo: "https://www.youtube.com/embed/rW0rKNk1F-c",
    image: courseImg,
  },
  {
    id: 8,
    title: "Cloud Computing Essentials",
    description: "Understand the basics of cloud computing and services.",
    about:
      "This course covers cloud service models, deployment methods, and provides hands-on experience with AWS and Azure.",
    duration: "8 Weeks",
    level: "Beginner",
    price: 180,
    rating: 4, // Rounded rating
    category: "Cloud Computing", // Category added
    curriculum: [
      "Week 1: Introduction to Cloud Computing",
      "Week 2: Cloud Service Models",
      "Week 3: AWS Overview",
      "Week 4: Azure Overview",
      "Week 5: Security in the Cloud",
      "Week 6: Cloud Deployment Models",
      "Week 7: Cost Management in Cloud Services",
      "Week 8: Final Assessment",
    ],
    youtubeVideo: "https://www.youtube.com/embed/VtRejcUQ-qE",
    image: courseImg,
  },
  {
    id: 9,
    title: "Cybersecurity Fundamentals",
    description: "Learn the basics of cybersecurity concepts and practices.",
    about:
      "This course covers essential topics in cybersecurity, including network security, cryptography, and security protocols.",
    duration: "10 Weeks",
    level: "Beginner to Intermediate",
    price: 220,
    rating: 5, // Rounded rating
    category: "Cybersecurity", // Category added
    curriculum: [
      "Week 1: Introduction to Cybersecurity",
      "Week 2: Cyber Threats and Attacks",
      "Week 3: Network Security Basics",
      "Week 4: Cryptography Fundamentals",
      "Week 5: Security Protocols",
      "Week 6: Risk Management",
      "Week 7: Security Frameworks",
      "Week 8: Incident Response",
      "Week 9: Final Project",
      "Week 10: Certification Preparation",
    ],
    youtubeVideo: "https://www.youtube.com/embed/3BIL8PIYwhM",
    image: courseImg,
  },
  {
    id: 10,
    title: "Mobile App Development with Flutter",
    description: "Build beautiful and high-performance mobile applications using Flutter.",
    about:
      "This course teaches you how to develop mobile apps using Flutter, covering UI design, state management, and API integration.",
    duration: "12 Weeks",
    level: "Beginner to Intermediate",
    price: 320,
    rating: 4, // Rounded rating
    category: "Mobile Development", // Category added
    curriculum: [
      "Week 1: Introduction to Flutter",
      "Week 2: Dart Programming Basics",
      "Week 3: Flutter Widgets",
      "Week 4: State Management",
      "Week 5: API Integration",
      "Week 6: Database Management",
      "Week 7: Responsive Design",
      "Week 8: Testing and Debugging",
      "Week 9: Deployment on iOS and Android",
      "Week 10: Final Project",
      "Week 11: Best Practices",
      "Week 12: Capstone Project",
    ],
    youtubeVideo: "https://www.youtube.com/embed/Ky6SqaMNNF8",
    image: courseImg,
  },
];
